# Generated by Django 5.2.6 on 2025-09-22 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("expression", models.TextField()),
                ("result", models.TextField()),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("scientific", "Scientific"),
                            ("matrix", "Matrix"),
                            ("graph", "Graphing"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("theme", models.CharField(default="dark", max_length=20)),
                ("decimal_places", models.IntegerField(default=10)),
                (
                    "angle_unit",
                    models.CharField(
                        choices=[("rad", "Radians"), ("deg", "Degrees")],
                        default="rad",
                        max_length=10,
                    ),
                ),
                (
                    "memory_value",
                    models.DecimalField(decimal_places=20, default=0, max_digits=50),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "session_key")},
            },
        ),
    ]
